#!/bin/bash
# It installs lmod

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

#install ntp, kernel, lmod and pdsh
install-packages -m mrsh-$DIB_HPC_BASE mrsh-rsh-compat-$DIB_HPC_BASE mrsh-server-$DIB_HPC_BASE
