#!/bin/bash

if [ "${DIB_DEBUG_TRACE:-0}" -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

case "$DIB_INIT_SYSTEM" in
    systemd)
        if [[ $DIB_HPC_IMAGE_TYPE == "compute" ]]; then
           systemctl enable xinetd
        fi
        ;;
    *)
        echo "Unsupported init system"
        exit 1
        ;;
esac
