#!bin/bash
# 
chpcInitPath=/tmp/CloudHPCInit
# if directory exists then mv to Old directory. TBD
mkdir -p $chpcInitPath
#copy Cloud HPC files to temp working directory
sudo cp -fr -L $CHPC_SCRIPTDIR/CloudHPCInit/* $chpcInitPath/
chpcInit=$chpcInitPath/chpcInit

#update sms_ip in cloudInit scripts
sudo sed -i -e "s/<sms_ip>/${sms_ip}/g" $chpcInit

# Update basic slurm configuration at sms node
perl -pi -e "s/^NodeName=(\S+)/NodeName=${cnodename_prefix}[1-${num_ccomputes}]/" /etc/slurm/slurm.conf
perl -pi -e "s/^PartitionName=normal Nodes=(\S+)/PartitionName=normal Nodes=${cnodename_prefix}[1-${num_ccomputes}]/" /etc/slurm/slurm.conf
# copy slurm file from sms node to Cloud Comute Nodes
cp -fr -L /etc/slurm/slurm.conf $chpcInitPath
#
##
# Copy other files needed for Cloud Init
sudo cp -fr /etc/passwd $chpcInitPath
sudo cp -fr /etc/shadow $chpcInitPath
sudo cp -fr /etc/group $chpcInitPath
sudo cp -fr /etc/slurm/slurm.conf $chpcInitPath
sudo cp -fr /etc/pam.d/slurm $chpcInitPath
sudo cp -fr /etc/munge/munge.key $chpcInitPath
#TBD: This is a workaround for now, what we want is nodes to communicate to other nodes and sms node. so need to update cn entries here. might want to generate a script which is executed on compute node, and that updates entries into /etc/hosts of compute node. This workaround will break other functionalities in Cloudburst scenario
sudo cp -fr /etc/hosts $chpcInitPath
