#!/bin/bash
#This script expects compute node ID as an input
set -x
# find and setup working directory
CHPC_SCRIPTDIR="$( cd "$( dirname "$( readlink -f "${BASH_SOURCE[0]}" )" )" && pwd -P )"
CHPC_SCRIPTDIR="${CHPC_SCRIPTDIR%x}"
cd $CHPC_SCRIPTDIR

echo "..$CHPC_SCRIPTDIR .."

# Create Post boot file, can be used for cloudInit
# Check for NTP server and configuration on compute nodes
#
#
# =====================================
# Preperation for CloudInit Script and files
# =====================================
# This assumes that HPC head node recipe is installed and SMS_node functionality is already configured. It will get some data from there to prepare cloudInit
#time source prepare_cloudInit
set +x
#
# ===========================
# Prepare CloudHPC Image : TODO
# ===========================
# Check if User selected to prepare cloud HPC images
time source prepare_chpc_image
# =========================
# Prepare OpenStack for HPC baremetal instances
# ==========================
prepare_chpc_openstack
#
# ========================================================
# Prepare SMS/Service Node. 
# Add Cloud baremetal nodes to HPC Orchestrator
# ========================================================
update_cnodes_to_sms

