#!/bin/bash

if [ "${DIB_DEBUG_TRACE:-0}" -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail
# remove key informations from tmp mount path
if [[ $DIB_HPC_IMAGE_TYPE == "sms" ]]; then
    # Before cleaning up, share sms public keys, so that it can be used with compute nodes for ssh
    if [ ! -d $DIB_HPC_SSH_PUB_KEY ] ; then
        install -d -m 700 $DIB_HPC_SSH_PUB_KEY
    fi
    if [ -e $TMP_HOOKS_PATH/authorized_keys ] ; then
        cat $TMP_HOOKS_PATH/authorized_keys >> $DIB_HPC_SSH_PUB_KEY/authorized_keys
    fi
    # clean up
    rm -fr $TMP_HOOKS_PATH/hpcasservice
    rm -fr TMP_HOOKS_PATH/authorized_keys
fi
