#!/bin/bash

cd "$(dirname "$0")"      || exit 1

source ./LOCAL_ENV        || exit 1
export BATS_JUNIT_CLASS=$TEST_DIR
source ./common/TEST_ENV  || exit 1
source ./common/functions || exit 1

echo " "
echo " "
echo "-------------------------------------------------------"
echo "Administrator Environment Tests"
echo "-------------------------------------------------------"

rm -f *.trs *.log *.log.xml

./clustershell
./conman
./ganglia
./genders
./mrsh
./munge
./nagios
./warewulf
./check_nodes
