#!/bin/bash
#This script expects compute node ID as an input
#set -x
# find and setup working directory
CHPC_SCRIPTDIR="$( cd "$( dirname "$( readlink -f "${BASH_SOURCE[0]}" )" )" && pwd -P )"
CHPC_SCRIPTDIR="${CHPC_SCRIPTDIR%x}"
cd $CHPC_SCRIPTDIR

echo "..$CHPC_SCRIPTDIR .."

# Create Post boot file, can be used for cloudInit
# Check for NTP server and configuration on compute nodes
#
#
# =====================================
# Preparation for CloudInit Script and files
# =====================================
# This assumes that HPC head node recipe is installed and SMS_node functionality is already configured. It will get some data from there to prepare cloudInit
time source prepare_cloud_init

# ========================
# Prepare CloudHPC Image :
# ========================
time source prepare_chpc_image

# ============================================
# create vpn tunnel to communication with openstack
# controller node
# ============================================-=
if [[ ${enable_vpn} -eq "1" ]]; then
    time source $CHPC_SCRIPTDIR/ovpn/setup_vpn_connection
fi
#
# =============================================
# Prepare OpenStack for HPC baremetal instances
# =============================================
time source extend_hpc_to_openstack


#Wait for CN(s) to come up. TODO: Poll and wait rather than just a set 10 minutes.
sleep 600

#Call cloudInit workaround script
#time source c_init_workaround
#
# ========================================================
# Prepare SMS/Service Node. 
# Add Cloud baremetal nodes to HPC Orchestrator
# ========================================================
time source update_cnodes_to_sms

