#!/bin/bash
# It installs lmod

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -e
set -o pipefail
DIB_DIB_NTP_SERVER=$DIB_NTP_SERVER
set -u

case "$DIB_INIT_SYSTEM" in
    systemd)
        if [ -e /etc/rsyslog.conf ]; then
            # Restart the rsyslog
            systemctl restart rsyslog
        fi

        # Enable InfiniBand
        systemctl enable rdma
        # Enable NTPD
        if [[ $DIB_HPC_IMAGE_TYPE == "compute" ]]; then
            systemctl enable ntpd
        fi
        #Enable NTPD on sms node
        if [[ $DIB_HPC_IMAGE_TYPE == "sms" ]]; then
            if [[ ! -z "${DIB_DIB_NTP_SERVER}" ]]; then
               echo "server ${DIB_DIB_NTP_SERVER}" >> /etc/ntp.conf 
            fi
            systemctl enable ntpd.service
            systemctl enable nfs-server
        fi
        ;;
    *)
        echo "Unsupported init system"
        exit 1
        ;;
esac
 

