#!/bin/bash

if [ "${DIB_DEBUG_TRACE:-0}" -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

case "$DIB_INIT_SYSTEM" in
    systemd)
        #enable & start slurmctrl and munge
        if [[ $DIB_HPC_IMAGE_TYPE == "sms" ]]; then
            systemctl enable munge
            systemctl enable slurmctld
            systemctl start munge
            systemctl start slurmctld
        fi
        ;;

    *)
        echo "Unsupported init system"
        exit 1
        ;;
esac
