#!bin/bash
# 
if [[ "${chpc_base}" == "orch" ]]; then
	echo "CloudInit: Intel Orchestrator"
        chpcInitPath=/opt/intel/hpc-orchestrator/admin/CloudHPCInit
else
	echo "CloudInit: OpenHPC - ${chpc_base}"
        chpcInitPath=/opt/ohpc/admin/CloudHPCInit
fi

# if directory exists then mv to Old directory. TBD
mkdir -p $chpcInitPath
#copy Cloud HPC files to temp working directory
sudo cp -fr -L ${SCRIPTDIR}/CloudHPCInit/${chpc_base}/* $chpcInitPath/
export chpcInit=$chpcInitPath/chpcInit

#update sms_ip in cloudInit scripts
sudo sed -i -e "s/<sms_ip>/${sms_ip}/g" $chpcInit

# Update basic slurm configuration at sms node
perl -pi -e "s/Nodes=*/Nodes=${cnodename_prefix}[1-${num_ccomputes}],/" /etc/slurm/slurm.conf
echo "NodeName=${cnodename_prefix}[1-${num_ccomputes}] State=UNKNOWN" >> /etc/slurm/slurm.conf
systemctl restart slurmctld

# We don't create a separate partition as of now, instead just extend the 
# HPC cluster partition with cloud provisioned compute nodes
#perl -pi -e "s/^PartitionName=normal Nodes=(\S+)/PartitionName=normal Nodes=${cnodename_prefix}[1-${num_ccomputes}]/" /etc/slurm/slurm.conf

# copy slurm file from sms node to Cloud Comute Nodes
cp -fr -L /etc/slurm/slurm.conf $chpcInitPath
#
##
# Copy other files needed for Cloud Init
sudo cp -fr /etc/passwd $chpcInitPath
sudo cp -fr /etc/shadow $chpcInitPath
sudo cp -fr /etc/group $chpcInitPath
sudo cp -fr /etc/slurm/slurm.conf $chpcInitPath
sudo cp -fr /etc/pam.d/slurm $chpcInitPath
sudo cp -fr /etc/munge/munge.key $chpcInitPath
#TBD: This is a workaround for now, what we want is nodes to communicate to other nodes and sms node. so need to update cn entries here. might want to generate a script which is executed on compute node, and that updates entries into /etc/hosts of compute node. This workaround will break other functionalities in Cloudburst scenario
sudo cp -fr /etc/hosts $chpcInitPath

# export CloudInit Path to nfs share
cat /etc/exports | grep "$chpcInitPath"
chpcInitPath_exported=$?

if [ "${chpcInitPath_exported}" -ne "0" ]; then
    echo "$chpcInitPath *(rw,no_subtree_check,no_root_squash)" >> /etc/exports
    exportfs -a
    systemctl restart nfs
    systemctl enable nfs-server
fi

