#!/bin/bash
# It installs lmod

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

# Install Development Tools

install-packages -g $DIB_HPC_BASE-autotools
install-packages valgrind-$DIB_HPC_BASE EasyBuild-$DIB_HPC_BASE spack-$DIB_HPC_BASE R_base-$DIB_HPC_BASE

# Install Compilers
install-packages $DIB_HPC_COMPILER-compilers-$DIB_HPC_BASE
# Install MPI Stack
for cmp in $DIB_HPC_COMPILER; do
   for mpi in $DIB_HPC_MPI; do
      DIB_INSTALL_MPI=$mpi-$cmp-$DIB_HPC_BASE
      install-packages $DIB_INSTALL_MPI 
   done
done

# Install Performance Tools
for cmp in $DIB_HPC_COMPILER; do
    install-packages $DIB_HPC_BASE-$cmp-$DIB_HPC_PERF_TOOLS
    # Install defaults for mvapich2
    if [[ $DIB_HPC_MPI == *mvapich2* ]]; then
       install-packages lmod-defaults-$cmp-mvapich2-$DIB_HPC_BASE 
    fi
    # Install 3rd party libraries
    for libs in $DIB_HPC_3RD_LIBS; do
        install-packages $DIB_HPC_BASE-$cmp-$libs
    done
done
# Install parallel libmeta-packages for all available MPIT tool chains
for cmp in $DIB_HPC_COMPILER; do
   for mpi in $DIB_HPC_MPI; do
      DIB_INSTALL_PARALLEL_META=$DIB_HPC_BASE-$cmp-$mpi-parallel-libs
      install-packages $DIB_INSTALL_PARALLEL_META
   done
done


# Install yum-utils
install-packages yum-utils
