#!bin/bash
function setup_dib() {
        #enable local disk-image-builder
        # Check if disk-image-builder is installed
        yum -y install diskimage-builder PyYAML
        #install grub dependency
        yum -y install parted
        # copy patch to installed location
        sudo cp -fr ../../dib/patch/* /usr/share/diskimage-builder/
}
function setup_dib_hpc_base() {
        # Install dib if it is not already installed
        setup_dib
        # For Debugging enable user
        #export PATH=/home/ppk/PPK/dib/dev/diskimage-builder/bin:/home/ppk/PPK/dib/dev/dib-utils/bin:$PATH
        # if cloudinit does not work then we will use this user for debugging
        export DIB_DEV_USER_USERNAME=chpc
        export DIB_DEV_USER_PASSWORD=intel8086
        export DIB_DEV_USER_PWDLESS_SUDO=1
        #setup NTP server
        export DIB_NTP_SERVER=$ntp_server
        # For debugging enable DEBUG_TRACE
        #export DIB_DEBUG_TRACE=1
        # Add our custom element path
        export ELEMENTS_PATH="$(realpath ../../dib/hpc/elements)"
        # path to hpc configuration files i.e. cloud.cfg
        export DIB_HPC_FILE_PATH="$(realpath ../../dib/hpc/hpc-files/)"
        # define base for image as ohpc or orch.
        export DIB_HPC_BASE=${chpc_base}

        #Path to HPC base yum repo file
        # We support either Intel HPC Orchestrator and OpenHPC
        if [[ "${DIB_HPC_BASE}" == "orch" ]]; then
            export DIB_YUM_REPO_CONF=/etc/yum.repos.d/HPC_Orchestrator.repo
            # for orch define Packge path
            # This file is used to install orch component inside image
            export DIB_HPC_ORCH_PKG=${orch_iso_path}
        else
            # Install the OpenHPC rpm
            yum -y install ${ohpc_pkg}	
            export DIB_HPC_OHPC_PKG=${ohpc_pkg}
        fi
        DIB_HPC_ELEMENTS="hpc-env-base"
}

function prepare_sms_image() {
    if [[ ${chpc_create_new_image} -ne 1 ]] && [[ -s $chpc_image_sms ]]; then
        # No need to create an image, image is provided by user
        echo -n "Skiping cloud sms-image build, Image provided:"
        echo "$chpc_image_sms"
        CHPC_IMAGE_DEST=$CHPC_CLOUD_IMAGE_PATH/$(basename $chpc_image_sms)
        if [[ ! -e $CHPC_IMAGE_DEST ]]; then
            sudo cp $chpc_image_sms $CHPC_CLOUD_IMAGE_PATH
        fi
        chpc_image_sms=$CHPC_IMAGE_DEST
    else
        echo "Building new User Image"
        # First setup diskimage-builder
        setup_dib_hpc_base

        # tell to build sms node image
        export DIB_HPC_IMAGE_TYPE=sms
 
        # enable Resource Manager
        DIB_HPC_ELEMENTS+=" hpc-slurm"
        
        #add mrsh if it is enabled
        if [[ ${enable_mrsh} -eq 1 ]];then
           DIB_HPC_ELEMENTS+=" hpc-mrsh"
        fi
        # for sms node setup dev environment
        export DIB_HPC_COMPILER="gnu"
        export DIB_HPC_MPI="openmpi mvapich2"
        export DIB_HPC_PERF_TOOLS="perf-tools"
        export DIB_HPC_3RD_LIBS="serial-libs parallel-libs io-libs python-libs runtimes"
        DIB_HPC_ELEMENTS+=" hpc-dev-env"
        # build an image
        echo "====================================================================="
        echo "=== Preparing cloud-hpc user image =================================="
        echo "====================================================================="
        disk-image-create centos7 vm local-config dhcp-all-interfaces devuser selinux-permissive $DIB_HPC_ELEMENTS -o icloud-hpc-cent7-sms 
        echo "====================================================================="
        echo "=== User Image Creation complete ===================================="
        echo "====================================================================="
        # User Image is reday
        chpc_image_sms="$( realpath icloud-hpc-cent7-sms.qcow2)"
        mkdir -p $CHPC_CLOUD_IMAGE_PATH 
        mv -f $chpc_image_sms $CHPC_CLOUD_IMAGE_PATH 
        chpc_image_sms=$CHPC_CLOUD_IMAGE_PATH/$(basename $chpc_image_sms)
    fi 
}
function prepare_user_image() {
    if [[ ${chpc_create_new_image} -ne 1 ]] && [[ -s $chpc_image_user ]]; then
        # No need to create an image, image is provided by user
        echo -n "Skiping cloud user-image build, Image provided:"
        echo "$chpc_image_user"
        CHPC_IMAGE_DEST=$CHPC_CLOUD_IMAGE_PATH/$(basename $chpc_image_user)
        if [[ ! -e $CHPC_IMAGE_DEST ]]; then
            sudo cp $chpc_image_user $CHPC_CLOUD_IMAGE_PATH
        fi
        chpc_image_user=$CHPC_IMAGE_DEST
    else
        echo "Building new User Image"
        # First setup diskimage-builder
        setup_dib_hpc_base

        # tell to build compute node image
        export DIB_HPC_IMAGE_TYPE=compute

        # enable Resource Manager
        DIB_HPC_ELEMENTS+=" hpc-slurm"
        
        # add mrsh if it is enabled
        if [[ ${enable_mrsh} -eq 1 ]];then
           DIB_HPC_ELEMENTS+=" hpc-mrsh"
        fi
        # build an image
        echo "====================================================================="
        echo "=== Preparing cloud-hpc user image =================================="
        echo "====================================================================="
        disk-image-create centos7 vm local-config dhcp-all-interfaces devuser selinux-permissive $DIB_HPC_ELEMENTS -o icloud-hpc-cent7 
        echo "====================================================================="
        echo "=== User Image Creation complete ===================================="
        echo "====================================================================="
        # User Image is reday
        chpc_image_user="$( realpath icloud-hpc-cent7.qcow2)"
        mkdir -p $CHPC_CLOUD_IMAGE_PATH 
        mv -f $chpc_image_user $CHPC_CLOUD_IMAGE_PATH 
        chpc_image_user=$CHPC_CLOUD_IMAGE_PATH/$(basename $chpc_image_user)
    fi 
}

function prepare_deploy_image() {
    if [[ ${chpc_create_new_image} -ne 1 ]] && [[ -s $chpc_image_deploy_kernel ]] && [[ -s $chpc_image_deploy_ramdisk ]]; then
        # No need to create an image, image is provided by user
        echo "Skiping cloud deploy-image build, Image provided:"
        echo "Deploy kernel Image:$chpc_image_deploy_kernel"
        echo "Deploy ramdisk Image:$chpc_image_deploy_ramdisk"
        #Store Images file
        CHPC_IMAGE_DEST=$CHPC_CLOUD_IMAGE_PATH/$(basename $chpc_image_deploy_kernel)
        if [[ ! -e $CHPC_IMAGE_DEST ]]; then
            sudo cp -f $chpc_image_deploy_kernel $CHPC_CLOUD_IMAGE_PATH/
        fi
        chpc_image_deploy_kernel=$CHPC_IMAGE_DEST
        CHPC_IMAGE_DEST=$CHPC_CLOUD_IMAGE_PATH/$(basename $chpc_image_deploy_ramdisk)
        if [[ ! -e $CHPC_IMAGE_DEST ]]; then
            sudo cp -f $chpc_image_deploy_ramdisk $CHPC_CLOUD_IMAGE_PATH/
        fi
        chpc_image_deploy_ramdisk=$CHPC_IMAGE_DEST
    else
        echo "Building new Cloud Deploy Image"
        echo "====================================================================="
        echo "=== Preparing cloud-hpc deploy images for ironic====================="
        echo "====================================================================="
        #prepare deploy images
        # Install dib if it is not already installed
        setup_dib
        # Unset any previos envirnment flag
        unset DIB_YUM_REPO_CONF
        #Install git if it is not already installed
        yum -y install git
        # make sure to get ironic component from stable ocata release
        export DIB_REPOREF_ironic_agent=stable/ocata

        disk-image-create ironic-agent centos7 -o icloud-hpc-deploy-c7
        echo "====================================================================="
        echo "=== cloud-hpc deploy images Complete ================================"
        echo "====================================================================="
        chpc_image_deploy_kernel="$( realpath icloud-hpc-deploy-c7.kernel)"
        chpc_image_deploy_ramdisk="$( realpath icloud-hpc-deploy-c7.initramfs)"
        #Store Images file
        mkdir -p $CHPC_CLOUD_IMAGE_PATH/
        sudo mv -f $chpc_image_deploy_kernel $CHPC_CLOUD_IMAGE_PATH/
        chpc_image_deploy_kernel=$CHPC_CLOUD_IMAGE_PATH/$(basename $chpc_image_deploy_kernel)
        sudo mv -f $chpc_image_deploy_ramdisk $CHPC_CLOUD_IMAGE_PATH/
        chpc_image_deploy_ramdisk=$CHPC_CLOUD_IMAGE_PATH/$(basename $chpc_image_deploy_ramdisk)
    fi
}

if [[ "${chpc_base}" == "orch" ]]; then 
    CHPC_CLOUD_IMAGE_PATH=/opt/intel/hpc-orchestrator/admin/images/cloud/
else
    CHPC_CLOUD_IMAGE_PATH=/opt/ohpc/admin/images/cloud/
fi

mkdir -p $CHPC_CLOUD_IMAGE_PATH
### Build HPC user image
echo "########################################################################"
echo "########################### Starting Image   ###########################"
echo "########################################################################"
prepare_sms_image
echo $chpc_image_sms
echo "########################################################################"
echo "########################### sms image is done ##########################"
echo "########################################################################"
prepare_user_image
echo $chpc_image_user
echo "########################################################################"
echo "########################### user image is done #########################"
echo "########################################################################"
#### Build hpc deploy image
prepare_deploy_image
echo $chpc_image_deploy_kernel
echo $chpc_image_deploy_ramdisk
echo "########################################################################"
echo "########################### deploy image is done #######################"
echo "########################################################################"
