#!/bin/bash
# It installs lmod

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

#install ntp, kernel, lmod and pdsh
install-packages ntp kernel lmod-$DIB_HPC_BASE pdsh-$DIB_HPC_BASE
#install infiniband support
# TBD need to try with element mellanox, if that work then need to remove following 2 lines
install-packages -g "InfiniBand Support"
install-packages  infinipath-psm

# Configure the rsyslog 
if [ -e /etc/rsyslog.conf ]; then
    #comment out unwanted messages, reduce noice
    sed -e "s/^\*\.info/\\#\*\.info/" /etc/rsyslog.conf
    sed -e "s/^authpriv/\\#authpriv/" /etc/rsyslog.conf
    sed -e "s/^mail/\\#mail/" /etc/rsyslog.conf
    sed -e "s/^cron/\\#cron/" /etc/rsyslog.conf
    sed -e "s/^uucp/\\#uucp/" /etc/rsyslog.conf
    #restart the rsyslog
    case "$DIB_INIT_SYSTEM" in
        systemd)
            systemctl restart rsyslog
            #enable infiniBand
            systemctl enable rdma
            # update mem limit
            sed -i -- 's/# End of file/\* hard memlock unlimited\n&/' /etc/security/limits.conf
            ;;
        *)
            echo "Unsupported init system"
            exit 1
            ;;
    esac
fi

#configure Cloud-Init
if [ -f $TMP_HOOKS_PATH/cloud.cfg ]; then
    sudo cp -L -f $TMP_HOOKS_PATH/cloud.cfg /etc/cloud/
fi
