#!/bin/bash
# It installs lmod

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

# Install slurm Server
if [[ $DIB_HPC_IMAGE_TYPE == "sms" ]]; then
   install-packages -g $DIB_HPC_BASE-slurm-server
fi
#install slurm Client
install-packages -g $DIB_HPC_BASE-slurm-client

# Update slurm pam module for mrsh and mrlogin
if [[ -f "/etc/pam.d/mrsh" && -f "etc/pam.d/mrlogin" ]]; then
   echo "account    required     pam_slurm.so" >> /etc/pam.d/mrsh
   echo "account    required     pam_slurm.so" >> /etc/pam.d/mrlogin
fi
#update slurm pam module for sshd
if [[ -f "/etc/pam.d/sshd" ]]; then
   echo "account    required     pam_slurm.so" >> /etc/pam.d/sshd
fi
