#!/bin/bash

cd "$(dirname "$0")"      || exit 1

source ./LOCAL_ENV        || exit 1
export BATS_JUNIT_CLASS=$TEST_DIR

echo " "
echo " "
echo "-------------------------------------------------------"
echo "Base OS Environment"
echo "-------------------------------------------------------"

rm -f *.log *.trs *.xml

./ibv_devinfo
./os_distribution
./computes
